server:
  port: ${PORT:${SERVER_PORT:0}}

jwt:
  secret: oYdmMqiysWb11whE8rNa1Uz84hB66f5i
  expiration_time: 864000000

spring:
  datasource:
    url: jdbc:mysql://localhost/monitordb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrival=true
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        forma_sql: true

logging:
  level: 
    org:
      hibernate: 
        sql: DEBUG
        type: 
          descriptor:
            sql:
              BasicBinder: TRACE

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

routes:
  roleRoutes:
    -
      uri: /api/v1/user/my
      method: GET
      roles:
        -
          ALL
    - uri: /api/v1/courses/course/{1}[0-9]+[0-9]*
      method: GET
      roles:
        -
          ALL
    -
      uri: /api/v1/teacher/
      method: GET
      roles:
        -
          ROLE_TEACHER
    -
      uri: /api/v1/council
      method: GET
      roles:
        -
          ROLE_COUNCIL
    - uri: /api/v1/structural/courses?studentId={1}[0-9]+[0-9]*
      method: GET
      roles:
        - ROLE_STUDENT
    -
      uri: /api/v1/login
      method: POST
      roles:
        -
          PUBLIC