server:
  port:8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: auth-service
            authorization-grant-type: authorization_code
            scope: openid
            issuer-uri: http://localhost:9090/realms/auth-service-realm
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/auth-service-realm
  cloud:
    gateway:
      discovery:
        locator:
        enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
