server:
  port:8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/auth-service-realm
          jwt-set-uri: http://localhost:9090/realms/auth-service-realm/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            token-uri: http://localhost:9090/realms/auth-service-realm/protocol/openid-connect/token
            authorization-uri: http://localhost:9090/realms/auth-service-realm/protocol/openid-connect/auth
            userinfo-uri: http://localhost:9090/realms/auth-service-realm/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
            user-name-authentication-method: header
        registration:
          keycloak:
            provider: keycloak
            client-id: auth-service
            client-secret: cWJag3yAN32NZ6AzKb5kqHFeEppX8wvX
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            scope: openid
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200/"
            allowedHeaders: "*"
            allowedMethods: "*"
      discovery:
        locator:
        enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/**
        - id: request-service
          uri: lb://request-service
          predicates:
            - Path=/api/v1/request/**

